apiVersion: v1
kind: Service
metadata:
  name: autodeploy42
  namespace: namespace-workflow-1708428870385
spec:
  type: LoadBalancer
  selector:
    app: autodeploy42
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000